# Generated by Django 5.1.2 on 2024-11-24 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('enrolled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='myapp.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
